// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset, StoryblokMultilink, StoryblokRichtext, StoryblokMultiasset } from '../storyblok.d.ts';
export interface Banner {
  memberLevel?: "" | "all" | "onlyMembers" | "member" | "silver" | "gold" | "hideMembers";
  image?: StoryblokAsset;
  imageMobile?: StoryblokAsset;
  imageAlt?: string;
  mobileOverlay?: boolean;
  mobileOverlayColor?: unknown;
  vimeo?: unknown;
  vimeoMobile?: unknown;
  blocks?: (SubTitle | Title | Button | Grid)[];
  placement?:
    | ""
    | "top-left"
    | "top-center"
    | "top-right"
    | "middle-left"
    | "middle-center"
    | "middle-right"
    | "bottom-left"
    | "bottom-center"
    | "bottom-right";
  alignItems?: "" | "left" | "center" | "right";
  desktopBannerWidth?: unknown;
  desktopBannerHeight?: "" | "small" | "medium" | "large" | "xlarge" | "screen";
  mobileBannerWidth?: unknown;
  mobileBannerHeight?: "" | "small" | "medium" | "large" | "xlarge" | "screen";
  url?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  Size?: unknown;
  component: "banner";
  _uid: string;
  [k: string]: unknown;
}

export interface BannerGrid {
  memberLevel?: "" | "all" | "onlyMembers" | "member" | "silver" | "gold" | "hideMembers";
  blocks?: Banner[];
  desktopGridWidth?: "" | "full" | "container";
  mobileGridWidth?: "" | "full" | "container";
  desktopColumns?: unknown;
  desktopRows?: unknown;
  mobileColumns?: unknown;
  mobileRows?: unknown;
  desktopGap?: unknown;
  mobileGap?: unknown;
  marginTop?: unknown;
  marginBottom?: unknown;
  Format?: "" | "16-9" | "1-1" | "9-16" | "16-8" | "16-7";
  display?: unknown;
  desktopGrid?: unknown;
  mobileGrid?: unknown;
  component: "bannerGrid";
  _uid: string;
  [k: string]: unknown;
}

export interface Blog {
  MainImage?: StoryblokAsset;
  seo?: unknown;
  Title?: string;
  ShortDescription?: string;
  Tags?: ("" | "mode")[];
  Date?: string;
  Content?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  component: "Blog";
  _uid: string;
  [k: string]: unknown;
}

export interface Button {
  text: string;
  url?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  size?: "" | "xsmall" | "small" | "medium" | "large" | "xlarge" | "xlarge2" | "xlarge3";
  icon?: "" | "arrow_right" | "arrow_left" | "undefined";
  iconColor?: unknown;
  font?: "" | "primary" | "secondary" | "base" | "title" | "accent";
  rounded?: boolean;
  shadow?: boolean;
  underline?: boolean;
  colorPickerText?: unknown;
  colorPickerBackground?: unknown;
  opacity?: unknown;
  marginBottom?: unknown;
  marginTop?: unknown;
  marginRight?: unknown;
  colorPickerBorder?: unknown;
  border?: unknown;
  component: "button";
  _uid: string;
  [k: string]: unknown;
}

export interface CategoryPage {
  title?: string;
  subtitle?: string;
  description?: string;
  heroImage?: StoryblokAsset;
  blocks?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  component: "categoryPage";
  _uid: string;
  [k: string]: unknown;
}

export interface CmsPage {
  title?: string;
  backgroundColor?: unknown;
  blocks?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  guides?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  seo?: unknown;
  component: "cmsPage";
  _uid: string;
  [k: string]: unknown;
}

export interface CmsPageHeader {
  title?: string;
  subtitle?: string;
  backgroundColor?: unknown;
  description?: string;
  titleSize?: "" | "large" | "xlarge" | "xlarge2" | "xlarge3" | "xlarge4" | "xlarge5";
  titleColor?: unknown;
  layout?: "" | "simple" | "overlay";
  paddingBottom?: unknown;
  component: "CmsPageHeader";
  _uid: string;
  [k: string]: unknown;
}

export interface CollectionItem {
  image?: StoryblokAsset;
  title?: string;
  slug?: string;
  collectionTitleColor?: unknown;
  component: "collectionItem";
  _uid: string;
  [k: string]: unknown;
}

export interface CollectionPage {
  heroImage?: StoryblokAsset;
  hidePill?: boolean;
  collectionSortOrder?: string;
  title?: string;
  customTitle?: string;
  CollectionDescription?: string;
  storyblokDescription?: StoryblokRichtext;
  hideTitle?: boolean;
  hideDescription?: boolean;
  hideBreadcrumbs?: boolean;
  blocks?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  release_date?: string;
  footerSeoTitle?: string;
  footerSeoDescription?: string;
  staticShoplab?: unknown;
  hide?: boolean;
  images?: StoryblokMultiasset;
  subtitle?: string;
  collectionMetaTitle?: string;
  collectionMetaDescription?: string;
  component: "collectionPage";
  _uid: string;
  [k: string]: unknown;
}

export interface Config {
  seo?: unknown;
  header_menu?: MenuLink[];
  usp?: Usp[];
  infoBar?: InfoBar[];
  infoBarUnder?: InfoBar[];
  intro_modal?: IntroBanner[];
  content?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  footer_menu?: Menu[];
  logos?: LogoItem[];
  component: "config";
  _uid: string;
  [k: string]: unknown;
}

export interface ConfigProduct {
  product_ups?: ProductUsp[];
  component: "config-product";
  _uid: string;
  [k: string]: unknown;
}

export interface ContentCard {
  title?: string;
  image: StoryblokAsset;
  imagePosition?: "" | "left" | "right";
  content?: StoryblokRichtext;
  ctaButtons?: Button[];
  subtitle?: string;
  backgroundColor?: unknown;
  mobileMarginTop?: unknown;
  mobileMarginBottom?: unknown;
  desktopMarginTop?: unknown;
  desktopMarginBottom?: unknown;
  component: "contentCard";
  _uid: string;
  [k: string]: unknown;
}

export interface CustomBeautyHeader {
  title?: string;
  description?: string;
  breadcrum?: boolean;
  backgroundColor?: unknown;
  component: "customBeautyHeader";
  _uid: string;
  [k: string]: unknown;
}

export interface ElevateProductSlider {
  Nyheter?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  component: "elevateProductSlider";
  _uid: string;
  [k: string]: unknown;
}

export interface Empty {
  blocks?: string;
  component: "empty";
  _uid: string;
  [k: string]: unknown;
}

export interface Entries {
  productItems?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  blocks?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  component: "entries";
  _uid: string;
  [k: string]: unknown;
}

export interface Entry {
  image: StoryblokAsset;
  preamble: string;
  title: string;
  buttonText?: string;
  link?: string;
  badge?: string;
  component: "entry";
  _uid: string;
  [k: string]: unknown;
}

export interface Faq {
  header?: string;
  blocks?: FaqRow[];
  footer?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  component: "faq";
  _uid: string;
  [k: string]: unknown;
}

export interface FaqCategory {
  title?: string;
  image?: StoryblokAsset;
  description?: string;
  slug?: string;
  paragraph1?: string;
  paragraph2?: string;
  paragraph3?: StoryblokRichtext;
  paragraph4?: StoryblokRichtext;
  component: "Faq category";
  _uid: string;
  [k: string]: unknown;
}

export interface FaqRow {
  title?: string;
  description?: string;
  component: "faq_row";
  _uid: string;
  [k: string]: unknown;
}

export interface Feature {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: unknown;
}

export interface FlexWithImage {
  image?: StoryblokAsset;
  items?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  component: "flexWithImage";
  _uid: string;
  [k: string]: unknown;
}

export interface GiftBlockItems {
  mainTitle?: string;
  blocks?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  component: "giftBlockItems";
  _uid: string;
  [k: string]: unknown;
}

export interface GiftBottomGrid {
  title?: string;
  items?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  component: "giftBottomGrid";
  _uid: string;
  [k: string]: unknown;
}

export interface GiftBottomItems {
  title?: string;
  description?: string;
  component: "giftBottomItems";
  _uid: string;
  [k: string]: unknown;
}

export interface GiftItems {
  ImageWithSubText?: StoryblokAsset;
  title?: string;
  subTitle?: string;
  url?: string;
  buttonText?: string;
  component: "gift-items";
  _uid: string;
  [k: string]: unknown;
}

export interface GiftsCardHeader {
  title?: string;
  subTitle?: string;
  description?: string;
  image?: StoryblokAsset;
  component: "giftsCardHeader";
  _uid: string;
  [k: string]: unknown;
}

export interface GiftsPage {
  title?: string;
  subTitle?: string;
  description?: string;
  blocks?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  image?: StoryblokAsset;
  bannerImage?: StoryblokAsset;
  component: "giftsPage";
  _uid: string;
  [k: string]: unknown;
}

export interface Grid {
  blocks?: (Entry | Product | Button | Faq | MemberBenefits | Title | Text | Section)[];
  mobileColumns: string;
  desktopColumns: string;
  mobileGap?: "" | "none" | "sm" | "md" | "lg" | "xl";
  desktopGap?: "" | "none" | "sm" | "md" | "lg";
  mobileVerticalSpacing?: "" | "none" | "sm" | "md" | "lg" | "xl";
  desktopVerticalSpacing?: "" | "none" | "sm" | "lg" | "xl" | "2xl";
  horizontalPadding?: "" | "none" | "sm" | "md" | "lg";
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface Hero {
  image: StoryblokAsset;
  addConfetti?: boolean;
  preamble: string;
  title: string;
  subtitle: string;
  buttonText?: string;
  placement?:
    | ""
    | "top-left"
    | "top-center"
    | "top-right"
    | "middle-center"
    | "middle-left"
    | "middle-right"
    | "bottom-left"
    | "bottom-center"
    | "bottom-right";
  Content?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  component: "hero";
  _uid: string;
  [k: string]: unknown;
}

export interface HeroHighlight {
  title?: string;
  subtitle?: string;
  image?: StoryblokAsset;
  titleColor?: unknown;
  titleSize?: "" | "large" | "xlarge" | "xlarge2" | "xlarge3" | "xlarge4" | "xlarge5";
  subtitleColor?: unknown;
  backgroundColor?: unknown;
  blocks?: (Button | Text)[];
  products?: unknown;
  findifyProducts?: string;
  itemCount?: string;
  component: "heroHighlight";
  _uid: string;
  [k: string]: unknown;
}

export interface HeroHighlightWithoutProducts {
  title?: string;
  subtitle?: string;
  image?: StoryblokAsset;
  titleColor?: unknown;
  titleSize?: "" | "large" | "xlarge" | "xlarge2" | "xlarge3" | "xlarge4" | "xlarge5";
  subtitleColor?: unknown;
  backgroundColor?: unknown;
  blocks?: (Button | Text)[];
  component: "heroHighlightWithoutProducts";
  _uid: string;
  [k: string]: unknown;
}

export interface HorizontalScrollGrid {
  title?: string;
  blocks?: HorizontalScrollGridCard[];
  height?: string;
  elementWidth?: string;
  scrollPercentage?: string;
  component: "horizontal-scroll-grid";
  _uid: string;
  [k: string]: unknown;
}

export interface HorizontalScrollGridCard {
  image?: StoryblokAsset;
  vimeo?: unknown;
  blocks?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  component: "horizontal-scroll-grid-card";
  _uid: string;
  [k: string]: unknown;
}

export interface ImageCardDisplay {
  headerText?: string;
  layoutMode?: "" | "grid" | "carousel";
  items?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  itemsPerView?: string;
  backgroundColor?: unknown;
  component: "imageCardDisplay";
  _uid: string;
  [k: string]: unknown;
}

export interface ImageCardDisplayItem {
  image?: StoryblokAsset;
  title?: string;
  ctaButtons?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  description?: string;
  imageHeight?: "" | "small" | "medium" | "large";
  backgroundColor?: unknown;
  component: "imageCardDisplayItem";
  _uid: string;
  [k: string]: unknown;
}

export interface ImageTextItems {
  image?: StoryblokAsset;
  items?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  imagePosition?: "" | "right" | "left";
  component: "imageTextItems";
  _uid: string;
  [k: string]: unknown;
}

export interface ImageWithText {
  title?: string;
  subTitle?: string;
  link?: string;
  linkText?: string;
  isBanner?: boolean;
  image?: StoryblokAsset;
  component: "imageWithText";
  _uid: string;
  [k: string]: unknown;
}

export interface InfoBar {
  content: StoryblokRichtext;
  colorPickerText?: unknown;
  colorPickerBackground?: unknown;
  memberLevel?: "" | "all" | "onlyMembers" | "member" | "silver" | "gold" | "hideMembers";
  component: "infoBar";
  _uid: string;
  [k: string]: unknown;
}

export interface IntroBanner {
  id: string;
  title?: string;
  message?: string;
  component: "introBanner";
  _uid: string;
  [k: string]: unknown;
}

export interface ItemCardDetails {
  image?: StoryblokAsset;
  title?: string;
  description?: string;
  itemDetailsBackgroundColor?: unknown;
  ctaButtons?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  component: "itemCardDetails";
  _uid: string;
  [k: string]: unknown;
}

export interface ItemCardDisplay {
  title?: string;
  titleSize?: "" | "large" | "xlarge" | "xlarge2" | "xlarge3" | "xlarge4" | "xlarge5";
  titleColor?: unknown;
  layoutMode?: "" | "carousel" | "grid";
  subtitle?: string;
  subTitleColor?: unknown;
  backgroundColor?: unknown;
  itemsPerView?: string;
  items?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  component: "itemCardDisplay";
  _uid: string;
  [k: string]: unknown;
}

export interface Link {
  text?: string;
  url?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "link";
  _uid: string;
  [k: string]: unknown;
}

export interface LinksGrid {
  links?: Link[];
  component: "linksGrid";
  _uid: string;
  [k: string]: unknown;
}

export interface LiveShopping {
  liveShoppingBanner?: (Button | LiveShoppingBanner)[];
  liveShoppingCards?: (LiveShoppingCard | Button)[];
  component: "Live Shopping";
  _uid: string;
  [k: string]: unknown;
}

export interface LiveShoppingBanner {
  showId: string;
  title: string;
  description: string;
  showButtonText?: string;
  image: StoryblokAsset;
  button?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  component: "liveShoppingBanner";
  _uid: string;
  [k: string]: unknown;
}

export interface LiveShoppingCard {
  showId: string;
  title: string;
  description: string;
  image: StoryblokAsset;
  component: "liveShoppingCard";
  _uid: string;
  [k: string]: unknown;
}

export interface LogoItem {
  logo: StoryblokAsset;
  title?: string;
  component: "logoItem";
  _uid: string;
  [k: string]: unknown;
}

export interface MalinTest {
  text?: string;
  block?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  textarea?: string;
  component: "malin test";
  _uid: string;
  [k: string]: unknown;
}

export interface MemberBenefits {
  title?: string;
  description?: string;
  blocks?: MemberBenefitsRow[];
  component: "member_benefits";
  _uid: string;
  [k: string]: unknown;
}

export interface MemberBenefitsRow {
  title?: string;
  member?: boolean;
  silver?: boolean;
  gold?: boolean;
  component: "member_benefits_row";
  _uid: string;
  [k: string]: unknown;
}

export interface Menu {
  title?: string;
  links: MenuLink[];
  component: "menu";
  _uid: string;
  [k: string]: unknown;
}

export interface MenuDivider {
  component: "menuDivider";
  _uid: string;
  [k: string]: unknown;
}

export interface MenuLink {
  subMenu?: SubMenu[];
  title: string;
  link: string;
  icon?: StoryblokAsset;
  component: "menuLink";
  _uid: string;
  [k: string]: unknown;
}

export interface Newsletter {
  mainImage?: StoryblokAsset;
  title: string;
  description: StoryblokRichtext;
  buttonText?: string;
  component: "newsletter";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  blocks?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  title?: string;
  subTitle?: string;
  description?: string;
  footer?: string;
  itemFooterBlocks?: GiftBottomGrid[];
  seo?: unknown;
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Paragragh {
  content?: string;
  component: "paragragh";
  _uid: string;
  [k: string]: unknown;
}

export interface Product {
  image?: StoryblokAsset;
  description?: StoryblokRichtext;
  hover_image?: StoryblokAsset;
  gallery?: StoryblokMultiasset;
  name?: string;
  price?: string;
  badge?: string;
  component: "product";
  _uid: string;
  [k: string]: unknown;
}

export interface ProductCardDisplay {
  title?: string;
  products?: unknown;
  layoutMode?: "" | "grid" | "carousel";
  itemsPerView?: string;
  backgroundColor?: unknown;
  component: "productCardDisplay";
  _uid: string;
  [k: string]: unknown;
}

export interface ProductGrid {
  products: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  component: "productGrid";
  _uid: string;
  [k: string]: unknown;
}

export interface ProductRecommendations {
  scrollable?: boolean;
  enableFindifyRecommendations?: boolean;
  component: "Product Recommendations";
  _uid: string;
  [k: string]: unknown;
}

export interface ProductSlider2 {
  numberOfProducts?: string;
  component: "productSlider2";
  _uid: string;
  [k: string]: unknown;
}

export interface ProductUsp {
  productUspSymbol?: StoryblokAsset;
  productUspTitle?: string;
  productUspSubTitle?: string;
  component: "productUsp";
  _uid: string;
  [k: string]: unknown;
}

export interface Profile {
  blocks?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  component: "Profile";
  _uid: string;
  [k: string]: unknown;
}

export interface RecommendedProducts {
  title?: string;
  itemCount: string;
  widgetId: string;
  blocks?: Button[];
  backgroundColor?: unknown;
  titleColor?: unknown;
  component: "recommendedProducts";
  _uid: string;
  [k: string]: unknown;
}

export interface Section {
  blocks?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  backgroundColor?: unknown;
  width?: "" | "full" | "container" | "narrow" | "wide" | "large" | "medium" | "small" | "xs";
  align?: "" | "left" | "center" | "right";
  verticalSpacing?: "" | "none" | "sm" | "md" | "lg";
  desktopHorizontalPadding?: "" | "none" | "sm" | "md" | "lg";
  mobileHorizontalPadding?: "" | "none" | "sm" | "md" | "lg";
  component: "section";
  _uid: string;
  [k: string]: unknown;
}

export interface SelfSelect {
  selectedProducts?: {
    [k: string]: unknown;
  }[];
  title?: string;
  subTitle?: string;
  description?: string;
  linkText?: string;
  url?: string;
  image?: StoryblokAsset;
  component: "self-select";
  _uid: string;
  [k: string]: unknown;
}

export interface SeoBlock {
  title?: string;
  backgroundColor?: unknown;
  blocks?: (SeoTitle | Text)[];
  seoLinks?: SeoLink[];
  component: "seoBlock";
  _uid: string;
  [k: string]: unknown;
}

export interface SeoLink {
  url?: string;
  label?: string;
  newTab?: boolean;
  component: "seoLink";
  _uid: string;
  [k: string]: unknown;
}

export interface SeoTitle {
  title?: string;
  component: "seoTitle";
  _uid: string;
  [k: string]: unknown;
}

export interface ShoplabCollections {
  title?: string;
  design?: "" | "grid" | "slide";
  collections?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  backgroundColor?: unknown;
  titleColor?: unknown;
  subtitleColor?: unknown;
  titleSize?: "" | "large" | "xlarge" | "xlarge2" | "xlarge3" | "xlarge5";
  subtitle?: string;
  collectionTitleColor?: unknown;
  component: "shoplabCollections";
  _uid: string;
  [k: string]: unknown;
}

export interface ShoplabProducts {
  title?: string;
  titleSize?: "" | "large" | "xlarge" | "xlarge2" | "xlarge3" | "xlarge4" | "xlarge5";
  newTitleColor?: unknown;
  backgroundColor?: unknown;
  products?: unknown;
  layoutMode?: "" | "grid" | "carousel";
  background?: StoryblokAsset;
  itemsPerView?: string;
  component: "shoplabProducts";
  _uid: string;
  [k: string]: unknown;
}

export interface SizeChart {
  size?: string;
  byst?: string;
  waist?: string;
  hips?: string;
  uk?: string;
  midja?: string;
  default?: string;
  stuss?: string;
  component: "sizeChart";
  _uid: string;
  [k: string]: unknown;
}

export interface SizeCharts {
  sizes?: SizeChart[];
  title: string;
  description?: string;
  component: "sizeCharts";
  _uid: string;
  [k: string]: unknown;
}

export interface SizeGuide {
  title?: string;
  settings?: (SizeGuideMeasure | SizeCharts | Button)[];
  button?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  component: "sizeGuide";
  _uid: string;
  [k: string]: unknown;
}

export interface SizeGuideItem {
  items?: SizeGuideItemRow[];
  component: "sizeGuideItem";
  _uid: string;
  [k: string]: unknown;
}

export interface SizeGuideItemRow {
  text?: string;
  logoText?: string;
  component: "sizeGuideItemRow";
  _uid: string;
  [k: string]: unknown;
}

export interface SizeGuideMeasure {
  items?: SizeGuideItemRow[];
  title: string;
  measureImage: StoryblokAsset;
  component: "sizeGuideMeasure";
  _uid: string;
  [k: string]: unknown;
}

export interface SplitSectionBlock {
  imagePosition?: "" | "left" | "right";
  contents?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  imageSize?: "" | "tall" | "standard" | "square";
  spacing?: "" | "standard" | "large" | "compact" | "none";
  image?: StoryblokAsset;
  component: "SplitSectionBlock";
  _uid: string;
  [k: string]: unknown;
}

export interface StorePage {
  title?: string;
  storeName?: string;
  city?: string;
  country: "" | "sverige" | "finland";
  address?: string;
  phone?: string;
  openHours?: string;
  blocks?: (
    | Banner
    | BannerGrid
    | Blog
    | Button
    | CategoryPage
    | CmsPage
    | CmsPageHeader
    | CollectionItem
    | CollectionPage
    | Config
    | ConfigProduct
    | ContentCard
    | CustomBeautyHeader
    | ElevateProductSlider
    | Empty
    | Entries
    | Entry
    | Faq
    | FaqCategory
    | FaqRow
    | Feature
    | FlexWithImage
    | GiftBlockItems
    | GiftBottomGrid
    | GiftBottomItems
    | GiftItems
    | GiftsCardHeader
    | GiftsPage
    | Grid
    | Hero
    | HeroHighlight
    | HeroHighlightWithoutProducts
    | HorizontalScrollGrid
    | HorizontalScrollGridCard
    | ImageCardDisplay
    | ImageCardDisplayItem
    | ImageTextItems
    | ImageWithText
    | InfoBar
    | IntroBanner
    | ItemCardDetails
    | ItemCardDisplay
    | Link
    | LinksGrid
    | LiveShopping
    | LiveShoppingBanner
    | LiveShoppingCard
    | LogoItem
    | MalinTest
    | MemberBenefits
    | MemberBenefitsRow
    | Menu
    | MenuDivider
    | MenuLink
    | Newsletter
    | Page
    | Paragragh
    | Product
    | ProductCardDisplay
    | ProductGrid
    | ProductRecommendations
    | ProductSlider2
    | ProductUsp
    | Profile
    | RecommendedProducts
    | Section
    | SelfSelect
    | SeoBlock
    | SeoLink
    | SeoTitle
    | ShoplabCollections
    | ShoplabProducts
    | SizeChart
    | SizeCharts
    | SizeGuide
    | SizeGuideItem
    | SizeGuideItemRow
    | SizeGuideMeasure
    | SplitSectionBlock
    | StorePage
    | SubMenu
    | SubMenuLink
    | SubTitle
    | Teaser
    | Text
    | Title
    | TitleSubtitleDescriptionText
    | TwoParagraphs
    | Usp
    | UspItem
  )[];
  positionLng?: string;
  positionLat?: string;
  seo?: unknown;
  component: "storePage";
  _uid: string;
  [k: string]: unknown;
}

export interface SubMenu {
  title?: string;
  subMenu?: SubMenuLink[];
  links: SubMenuLink[];
  image?: StoryblokAsset;
  component: "subMenu";
  _uid: string;
  [k: string]: unknown;
}

export interface SubMenuLink {
  title: string;
  link: string;
  image?: StoryblokAsset;
  component: "subMenuLink";
  _uid: string;
  [k: string]: unknown;
}

export interface SubTitle {
  title: string;
  type?: "" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  size?: "" | "xsmall" | "small" | "medium" | "large" | "xlarge" | "2xlarge" | "3xlarge";
  fontWeight?: "" | "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900" | "italic";
  font?: "" | "primary" | "secondary" | "base" | "title" | "accent";
  colorPicker?: unknown;
  opacity?: unknown;
  component: "subTitle";
  _uid: string;
  [k: string]: unknown;
}

export interface Teaser {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}

export interface Text {
  align?: "" | "left" | "center" | "right";
  content?: StoryblokRichtext;
  component: "text";
  _uid: string;
  [k: string]: unknown;
}

export interface Title {
  title: string;
  type?: "" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  font?: "" | "primary" | "secondary" | "base" | "title" | "accent";
  size?: "" | "xsmall" | "small" | "medium" | "large" | "xlarge" | "xlarge2" | "xlarge3" | "xxsmall";
  fontWeight?: "" | "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900";
  marginBottom?: unknown;
  shadow?: boolean;
  colorPicker?: unknown;
  opacity?: unknown;
  width?: "" | "full" | "container" | "large" | "medium" | "narrow" | "xs";
  component: "title";
  _uid: string;
  [k: string]: unknown;
}

export interface TitleSubtitleDescriptionText {
  title?: StoryblokRichtext;
  subTitle?: StoryblokRichtext;
  description?: StoryblokRichtext;
  component: "titleSubtitleDescriptionText";
  _uid: string;
  [k: string]: unknown;
}

export interface TwoParagraphs {
  description_1?: string;
  description_2?: string;
  component: "two-paragraphs";
  _uid: string;
  [k: string]: unknown;
}

export interface Usp {
  uspItems: UspItem[];
  component: "usp";
  _uid: string;
  [k: string]: unknown;
}

export interface UspItem {
  icon?: StoryblokAsset;
  title: string;
  component: "uspItem";
  _uid: string;
  [k: string]: unknown;
}
