// TODO: Validate list of CSP headers
const cspConfig = {
  defaultSrc: ["'self'"],
  connectSrc: [
    "'self'",
    'localhost:*',
    'https://*.findify.io',
    'https://*.googleapis.com',
    '*.google.com',
    'https://*.gstatic.com',
    'data:',
    'blob:',
    'ws:',
    'https://api.storyblok.com',
    'https://a.storyblok.com',
    `https://shopper.eu-west-1.${process.env.NEXT_PUBLIC_BRINK_ENV}.brinkcommerce.io`,
    'https://api.checkout.uat.walleydev.com',
    'https://eu.playground.klarnaevt.com',
    'https://checkoutshopper-test.adyen.com',
    'https://cognito-idp.eu-west-1.amazonaws.com/',
    'https://pagead2.googlesyndication.com',
    'https://cdn-cookieyes.com',
    'https://*.cookieyes.com',
    'https://*.doubleclick.net',
    'https://eu.klarnaevt.com',
    'https://*.clarity.ms/',
    'https://static.zdassets.com',
    'https://ekr.zdassets.com',
    'https://vimeo.com',
    'https://*.google-analytics.com/',
    'https://*.bambuser.com/',
    'https://cdn.liveshopping.bambuser.com',
    'https://www.googleadservices.com',
    'https://www.google.se',
    'https://www.google.com',
    'https://*.eu-north-1.aws.elastic-cloud.com:9243',
    'https://*.voyado.com',
    'https://*.fullstory.com',
    'https://*.klarna.com',
    'https://*.kustom.co',
    'https://*.pinterest.com',
  ],
  fontSrc: ["'self'", 'data:', 'https://fonts.gstatic.com', 'https://vercel.live'],
  formAction: ["'self'", 'https://localhost:3000/api/auth/signin/brink'],
  styleSrc: [
    "'self'",
    "'unsafe-eval'",
    "'unsafe-inline'",
    'https://fonts.googleapis.com',
    'https://localhost:3000',
    'https://app.storyblok.com',
    'https://fonts.gstatic.com',
    'https://www.googletagmanager.com',
    'https://vercel.live/fonts',
    'https://*.bambuser.com/',
  ],
  manifestSrc: ["'self'"],
  frameSrc: [
    'https://lcx-player.bambuser.com/',
    '*.google.com',
    'https://cdn-stage.ingrid.com',
    'https://checkout.uat.walleydev.com',
    'https://*.klarna.com',
    'https://*.kustom.co',
    'https://checkoutshopper-test.adyen.com',
    'https://pago.qit.nu',
    'https://vercel.live/',
    'https://www.googletagmanager.com/',
    'https://www.facebook.com/',
    'https://*.google.com',
    'https://player.vimeo.com',
    'https://lcx-embed.bambuser.com/',
    'https://td.doubleclick.net/',
    'https://www.googleadservices.com/',
    'https://cdn.liveshopping.bambuser.com/',
    'https://*.pinterest.com',
    'http://localhost:*',
    'https://cms.sp.tech',
    'https://dev.sp.tech',
  ],
  frameAncestors: [
    "'self'",
    'https://app.storyblok.com',
    'https://dev.sp.tech',
    'https://localhost:*',
    'http://localhost:*',
    'https://www.sp.tech',
    'https://cms.sp.tech',
  ],
  objectSrc: ["'self'", 'data:'],
  scriptSrc: [
    "'self'",
    "'unsafe-eval'",
    "'unsafe-inline'",
    'https://maps.googleapis.com',
    'https://localhost:3000',
    'https://app.storyblok.com',
    'https://cdn-stage.ingrid.com',
    'https://api.uat.walleydev.com',
    'https://*.klarna.com',
    'https://*.kustom.co',
    'https://pago.qit.nu',
    'https://cdn-cookieyes.com',
    'https://*.cookieyes.com',
    'https://*.clarity.ms',
    'https://*.facebook.net',
    'https://vercel.live',
    'https://static.zdassets.com',
    'https://*.vimeo.com',
    'https://*.google-analytics.com/',
    'https://lcx-embed.bambuser.com',
    'https://lcx-player.bambuser.com/',
    'https://*.googletagmanager.com',
    'https://tagmanager.google.com',
    'https://www.google-analytics.com',
    'https://*.voyado.com',
    'https://*.fullstory.com',
    'https://*.pinimg.com',
    'https://*.firebaseapp.com',
    'https://apis.google.com',
    'https://securetoken.googleapis.com',
    'https://identitytoolkit.googleapis.com',
    'https://*.firebase.googleapis.com',
    'https://script.crazyegg.com',
    'https://bat.bing.com',
    'https://t.myvisitors.se',
    'https://*.pinterest.com',
  ],
  workerSrc: ["'self'", 'blob:'],
  imgSrc: [
    'blob:',
    'data:',
    "'self'",
    "'unsafe-inline'",
    'https://*.googleapis.com',
    'https://*.gstatic.com',
    '*.google.com',
    '*.googleusercontent.com',
    'https://a.storyblok.com',
    'https://img2.storyblok.com',
    'd13fz3ub690kw1.cloudfront.net',
    'https://eu.playground.klarnaevt.com',
    'https://checkoutshopper-test.adyen.com',
    'https://*.cdn.adyen.com',
    'https://cdn.shoplab.io',
    'https://*.klarna.com',
    'https://*.kustom.co',
    'https://shoplab.b-cdn.net',
    'https://www.googletagmanager.com',
    'https://cdn-cookieyes.com',
    'https://s3.amazonaws.com',
    'https://eu.klarnaevt.com',
    'https://vercel.com',
    'https://www.facebook.com',
    'https://www.facebook.net',
    'https://lcx-embed.bambuser.com/',
    'https://lcx-player.bambuser.com/',
    'https://cdn.sanity.io',
    'https://*.pinterest.com',
    'https://bat.bing.com',
  ],
  mediaSrc: ["'self'", 'data:', 'blob:', 'localhost:*', 'https://a.storyblok.com'],
  baseUri: ["'self'"],
};

const generateCspHeader = (config) => {
  const cspHeader = Object.entries(config)
    .map(([key, values]) => {
      const filteredValues = [...new Set(values.map((value) => value.trim()).filter(Boolean))];
      return `${key.replace(/([A-Z])/g, '-$1').toLowerCase()} ${filteredValues.join(' ')};`;
    })
    .join(' ');

  return cspHeader;
};

const headers = async () => {
  const cspHeader = generateCspHeader(cspConfig);

  return [
    {
      source: '/(.*)',
      headers: [
        {
          key: 'Content-Security-Policy',
          value: cspHeader,
        },
      ],
    },
  ];
};

module.exports = { headers };
